subprojects {
    apply plugin: "java-library"

    group = project.property("GROUP_ID")
    version = project.property("VERSION_NAME")

    java {
        toolchain.languageVersion.set(JavaLanguageVersion.of(25))
    }

    repositories {
        gradlePluginPortal()
        mavenCentral()
        mavenLocal()
    }

    dependencies {
        testImplementation("org.junit.jupiter:junit-jupiter:5.11.0")
        testImplementation("org.junit-pioneer:junit-pioneer:2.2.0")
        testImplementation("com.google.truth:truth:1.4.1")
    }

    test {
        useJUnitPlatform()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release.set(25)
    }
}
